### ISSUE TITLE
Problem with source code download

### ISSUE THREAD

**Issue by pi-dev500** [twarped/Cracked-MultiMC-pi-apps#1]
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 01/19/2023
Latest Pi-Apps version: 01/19/2023
Kernel: aarch64 5.15.84-v8+
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.79 GB
Raspberry Pi OS image version: 2022-09-22
Language: en_US.UTF-8

BEGINNING OF LOG FILE:
-----------------------

Installing Necessary Dependencies
Will install these packages: lsb-release wget apt-transport-https gnupg 
Creating an empty apt-package to install the necessary apt packages...
It will be named: pi-apps-c24130a9
Depends: apt-transport-https, gnupg, lsb-release, wget
Running sudo apt update...
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:4 http://deb.debian.org/debian bullseye-updates InRelease
Hit:5 https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease
All packages are up to date.
apt update complete.
Installing the pi-apps-c24130a9 package...
The following package was automatically installed and is no longer required:
  libmodplug1:armhf
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  pi-apps-c24130a9
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Get:1 /home/pi-dev500/pi-apps-c24130a9.deb pi-apps-c24130a9 all 1.0 [800 B]
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 175968 files and directories currently installed.)

Unpacking pi-apps-c24130a9 (1.0) ...

Apt finished.
Package installation complete.
Adding AdoptOpenJDK repository:
- public key -> keyring
Downloading public to /tmp/adoptopenjdk-public-key... 
?25hKDone ———————————————————————————————————————————————————————————————————————————
gpg: keybox '/tmp/adoptopenjdk-keyring.gpg' created
gpg: key 8AC3B29174885C03: public key "AdoptOpenJDK (used for publishing RPM and DEB files) <adoptopenjdk@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
 - keyring -> GPG key
 - Moving GPG key to /usr/share/keyrings
 - Creating /etc/apt/sources.list.d/adoptopenjdk.list
 - Installing adoptopenjdk-16-hotspot-jre
Will install these packages: adoptopenjdk-16-hotspot-jre 
Waiting until APT locks are released... Done
Creating an empty apt-package to install the necessary apt packages...
It will be named: pi-apps-c24130a9
The pi-apps-c24130a9 package is already installed. Inheriting its dependencies: apt-transport-https, gnupg, lsb-release, wget
Depends: adoptopenjdk-16-hotspot-jre, apt-transport-https, gnupg, lsb-release, wget
Running sudo apt update...
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://security.debian.org/debian-security bullseye-security InRelease
Hit:4 http://deb.debian.org/debian bullseye-updates InRelease
Hit:5 https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease
Get:6 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb bullseye InRelease [6,159 B]
Get:7 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb bullseye/main armhf Packages [2,128 B]
Get:8 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb bullseye/main arm64 Packages [3,805 B]
Fetched 12.1 kB in 3s (3,909 B/s)
All packages are up to date.
apt update complete.
Installing the pi-apps-c24130a9 package...
The following package was automatically installed and is no longer required:
  libmodplug1:armhf
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  adoptopenjdk-16-hotspot-jre
The following NEW packages will be installed:
  adoptopenjdk-16-hotspot-jre
The following packages will be upgraded:
  pi-apps-c24130a9
1 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Get:1 /home/pi-dev500/pi-apps-c24130a9.deb pi-apps-c24130a9 all 1.0 [820 B]
Get:2 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb bullseye/main arm64 adoptopenjdk-16-hotspot-jre arm64 16.0.1+9-3 [48.0 MB]
apt-listchanges: Reading changelogs...
Fetched 48.0 MB in 17s (2,868 kB/s)
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 175968 files and directories currently installed.)

Unpacking adoptopenjdk-16-hotspot-jre (16.0.1+9-3) ...

Unpacking pi-apps-c24130a9 (1.0) over (1.0) ...

update-alternatives: using /usr/lib/jvm/adoptopenjdk-16-hotspot-jre-arm64/bin/jaotc to provide /usr/bin/jaotc (jaotc) in auto mode

update-alternatives: using /usr/lib/jvm/adoptopenjdk-16-hotspot-jre-arm64/bin/jfr to provide /usr/bin/jfr (jfr) in auto mode

update-alternatives: using /usr/lib/jvm/adoptopenjdk-16-hotspot-jre-arm64/bin/jrunscript to provide /usr/bin/jrunscript (jrunscript) in auto mode

update-alternatives: using /usr/lib/jvm/adoptopenjdk-16-hotspot-jre-arm64/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode

update-alternatives: using /usr/lib/jvm/adoptopenjdk-16-hotspot-jre-arm64/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode

update-alternatives: using /usr/lib/jvm/adoptopenjdk-16-hotspot-jre-arm64/bin/rmiregistry to provide /usr/bin/rmiregistry (rmiregistry) in auto mode

update-alternatives: using /usr/lib/jvm/adoptopenjdk-16-hotspot-jre-arm64/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode

update-alternatives: using /usr/lib/jvm/adoptopenjdk-16-hotspot-jre-arm64/lib/jspawnhelper to provide /usr/bin/jspawnhelper (jspawnhelper) in auto mode

Apt finished.
Package installation complete.
Adding Adoptium repository:
- public key -> keyring
Downloading public to /tmp/adoptium-public-key... 
?25hKDone ———————————————————————————————————————————————————————————————————————————
gpg: keybox '/tmp/adoptium-keyring.gpg' created
gpg: key 843C48A565F8F04B: public key "Adoptium GPG Key (DEB/RPM Signing Key) <temurin-dev@eclipse.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
 - keyring -> GPG key
 - Moving GPG key to /usr/share/keyrings
 - Creating /etc/apt/sources.list.d/adoptium.list
 - Installing temurin-8-jdk temurin-17-jdk
Will install these packages: temurin-8-jdk temurin-17-jdk 
Waiting until APT locks are released... Done
Creating an empty apt-package to install the necessary apt packages...
It will be named: pi-apps-c24130a9
The pi-apps-c24130a9 package is already installed. Inheriting its dependencies: adoptopenjdk-16-hotspot-jre, apt-transport-https, gnupg, lsb-release, wget
Depends: adoptopenjdk-16-hotspot-jre, apt-transport-https, gnupg, lsb-release, temurin-17-jdk, temurin-8-jdk, wget
Running sudo apt update...
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:5 https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease
Hit:6 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb bullseye InRelease
Get:7 https://adoptium.jfrog.io/artifactory/deb bullseye InRelease [6,638 B]
Get:8 https://adoptium.jfrog.io/artifactory/deb bullseye/main armhf Packages [3,588 B]
Get:9 https://adoptium.jfrog.io/artifactory/deb bullseye/main arm64 Packages [3,611 B]
Fetched 13.8 kB in 3s (4,165 B/s)
All packages are up to date.
apt update complete.
Installing the pi-apps-c24130a9 package...
The following package was automatically installed and is no longer required:
  libmodplug1:armhf
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  adoptium-ca-certificates p11-kit p11-kit-modules temurin-17-jdk temurin-8-jdk
The following NEW packages will be installed:
  adoptium-ca-certificates p11-kit p11-kit-modules temurin-17-jdk temurin-8-jdk
The following packages will be upgraded:
  pi-apps-c24130a9
1 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Get:1 /home/pi-dev500/pi-apps-c24130a9.deb pi-apps-c24130a9 all 1.0 [832 B]
Get:2 http://deb.debian.org/debian bullseye/main arm64 p11-kit-modules arm64 0.23.22-1 [216 kB]
Get:3 http://deb.debian.org/debian bullseye/main arm64 p11-kit arm64 0.23.22-1 [283 kB]
Get:4 https://adoptium.jfrog.io/artifactory/deb bullseye/main arm64 adoptium-ca-certificates all 1.0.1-1 [2,260 B]
Get:5 https://adoptium.jfrog.io/artifactory/deb bullseye/main arm64 temurin-17-jdk arm64 17.0.5.0.0+8 [163 MB]
Get:6 https://adoptium.jfrog.io/artifactory/deb bullseye/main arm64 temurin-8-jdk arm64 8.0.352.0.0+8-1 [83.6 MB]
apt-listchanges: Reading changelogs...
Fetched 247 MB in 1min 23s (2,971 kB/s)
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 176292 files and directories currently installed.)

Unpacking p11-kit-modules:arm64 (0.23.22-1) ...

Unpacking p11-kit (0.23.22-1) ...

Unpacking adoptium-ca-certificates (1.0.1-1) ...

Unpacking temurin-17-jdk (17.0.5.0.0+8) ...

Unpacking temurin-8-jdk (8.0.352.0.0+8-1) ...

Unpacking pi-apps-c24130a9 (1.0) over (1.0) ...

/etc/ssl/certs/adoptium/cacerts successfully populated.

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jar to provide /usr/bin/jar (jar) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jarsigner to provide /usr/bin/jarsigner (jarsigner) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/javadoc to provide /usr/bin/javadoc (javadoc) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/javap to provide /usr/bin/javap (javap) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jcmd to provide /usr/bin/jcmd (jcmd) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jconsole to provide /usr/bin/jconsole (jconsole) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jdb to provide /usr/bin/jdb (jdb) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jdeprscan to provide /usr/bin/jdeprscan (jdeprscan) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jdeps to provide /usr/bin/jdeps (jdeps) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jfr to provide /usr/bin/jfr (jfr) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jhsdb to provide /usr/bin/jhsdb (jhsdb) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jimage to provide /usr/bin/jimage (jimage) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jinfo to provide /usr/bin/jinfo (jinfo) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jlink to provide /usr/bin/jlink (jlink) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jmap to provide /usr/bin/jmap (jmap) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jmod to provide /usr/bin/jmod (jmod) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jpackage to provide /usr/bin/jpackage (jpackage) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jps to provide /usr/bin/jps (jps) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jrunscript to provide /usr/bin/jrunscript (jrunscript) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jshell to provide /usr/bin/jshell (jshell) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jstack to provide /usr/bin/jstack (jstack) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jstat to provide /usr/bin/jstat (jstat) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/jstatd to provide /usr/bin/jstatd (jstatd) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/rmiregistry to provide /usr/bin/rmiregistry (rmiregistry) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/bin/serialver to provide /usr/bin/serialver (serialver) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-17-jdk-arm64/lib/jspawnhelper to provide /usr/bin/jspawnhelper (jspawnhelper) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-8-jdk-arm64/bin/appletviewer to provide /usr/bin/appletviewer (appletviewer) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-8-jdk-arm64/bin/clhsdb to provide /usr/bin/clhsdb (clhsdb) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-8-jdk-arm64/bin/extcheck to provide /usr/bin/extcheck (extcheck) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-8-jdk-arm64/bin/hsdb to provide /usr/bin/hsdb (hsdb) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-8-jdk-arm64/bin/idlj to provide /usr/bin/idlj (idlj) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-8-jdk-arm64/bin/javah to provide /usr/bin/javah (javah) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-8-jdk-arm64/bin/jhat to provide /usr/bin/jhat (jhat) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-8-jdk-arm64/bin/jsadebugd to provide /usr/bin/jsadebugd (jsadebugd) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-8-jdk-arm64/bin/native2ascii to provide /usr/bin/native2ascii (native2ascii) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-8-jdk-arm64/bin/orbd to provide /usr/bin/orbd (orbd) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-8-jdk-arm64/bin/policytool to provide /usr/bin/policytool (policytool) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-8-jdk-arm64/bin/schemagen to provide /usr/bin/schemagen (schemagen) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-8-jdk-arm64/bin/servertool to provide /usr/bin/servertool (servertool) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-8-jdk-arm64/bin/tnameserv to provide /usr/bin/tnameserv (tnameserv) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-8-jdk-arm64/bin/wsgen to provide /usr/bin/wsgen (wsgen) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-8-jdk-arm64/bin/wsimport to provide /usr/bin/wsimport (wsimport) in auto mode

update-alternatives: using /usr/lib/jvm/temurin-8-jdk-arm64/bin/xjc to provide /usr/bin/xjc (xjc) in auto mode

Apt finished.
Package installation complete.
Will install these packages: build-essential libopenal1 x11-xserver-utils subversion git clang cmake curl zlib1g-dev openjdk-11-jdk qtbase5-dev 
Creating an empty apt-package to install the necessary apt packages...
It will be named: pi-apps-c24130a9
The pi-apps-c24130a9 package is already installed. Inheriting its dependencies: adoptopenjdk-16-hotspot-jre, apt-transport-https, gnupg, lsb-release, temurin-17-jdk, temurin-8-jdk, wget
Depends: adoptopenjdk-16-hotspot-jre, apt-transport-https, build-essential, clang, cmake, curl, git, gnupg, libopenal1, lsb-release, openjdk-11-jdk, qtbase5-dev, subversion, temurin-17-jdk, temurin-8-jdk, wget, x11-xserver-utils, zlib1g-dev
Running sudo apt update...
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://security.debian.org/debian-security bullseye-security InRelease
Hit:3 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:4 http://deb.debian.org/debian bullseye-updates InRelease
Hit:5 https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease
Hit:6 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb bullseye InRelease
Hit:7 https://adoptium.jfrog.io/artifactory/deb bullseye InRelease
All packages are up to date.
apt update complete.
Installing the pi-apps-c24130a9 package...
The following package was automatically installed and is no longer required:
  libmodplug1:armhf
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  clang libapr1 libaprutil1 libserf-1-1 libsvn1 libutf8proc2 libvulkan-dev
  qt5-qmake qt5-qmake-bin qtbase5-dev qtbase5-dev-tools qtchooser subversion
Suggested packages:
  default-libmysqlclient-dev firebird-dev libpq-dev libsqlite3-dev unixodbc-dev
  db5.3-util libapache2-mod-svn subversion-tools
Recommended packages:
  libqt5opengl5-dev
The following NEW packages will be installed:
  clang libapr1 libaprutil1 libserf-1-1 libsvn1 libutf8proc2 libvulkan-dev
  qt5-qmake qt5-qmake-bin qtbase5-dev qtbase5-dev-tools qtchooser subversion
The following packages will be upgraded:
  pi-apps-c24130a9
1 upgraded, 13 newly installed, 0 to remove and 0 not upgraded.
Get:1 /home/pi-dev500/pi-apps-c24130a9.deb pi-apps-c24130a9 all 1.0 [908 B]
Get:2 http://deb.debian.org/debian bullseye/main arm64 clang arm64 1:11.0-51+nmu5 [8,872 B]
Get:3 http://deb.debian.org/debian bullseye/main arm64 libapr1 arm64 1.7.0-6+deb11u1 [98.8 kB]
Get:4 http://deb.debian.org/debian bullseye/main arm64 libaprutil1 arm64 1.6.1-5 [89.6 kB]
Get:5 http://deb.debian.org/debian bullseye/main arm64 libserf-1-1 arm64 1.3.9-10 [52.6 kB]
Get:6 http://deb.debian.org/debian bullseye/main arm64 libutf8proc2 arm64 2.5.0-1 [54.2 kB]
Get:7 http://deb.debian.org/debian bullseye/main arm64 libsvn1 arm64 1.14.1-3+deb11u1 [1,320 kB]
Get:8 http://deb.debian.org/debian bullseye/main arm64 libvulkan-dev arm64 1.2.162.0-1 [586 kB]
Get:9 http://deb.debian.org/debian bullseye/main arm64 qt5-qmake-bin arm64 5.15.2+dfsg-9 [913 kB]
Get:10 http://deb.debian.org/debian bullseye/main arm64 qtchooser arm64 66-2 [24.9 kB]
Get:11 http://deb.debian.org/debian bullseye/main arm64 qt5-qmake arm64 5.15.2+dfsg-9 [249 kB]
Get:12 http://deb.debian.org/debian bullseye/main arm64 qtbase5-dev-tools arm64 5.15.2+dfsg-9 [716 kB]
Get:13 http://deb.debian.org/debian bullseye/main arm64 qtbase5-dev arm64 5.15.2+dfsg-9 [1,148 kB]
Get:14 http://deb.debian.org/debian bullseye/main arm64 subversion arm64 1.14.1-3+deb11u1 [978 kB]
apt-listchanges: Reading changelogs...
Fetched 6,238 kB in 4s (1,465 kB/s)
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 177424 files and directories currently installed.)

Unpacking clang (1:11.0-51+nmu5) ...

Unpacking libapr1:arm64 (1.7.0-6+deb11u1) ...

Unpacking libaprutil1:arm64 (1.6.1-5) ...

Unpacking libserf-1-1:arm64 (1.3.9-10) ...

Unpacking libutf8proc2:arm64 (2.5.0-1) ...

Unpacking libsvn1:arm64 (1.14.1-3+deb11u1) ...

Unpacking libvulkan-dev:arm64 (1.2.162.0-1) ...

Unpacking qt5-qmake-bin (5.15.2+dfsg-9) ...

Unpacking qtchooser (66-2) ...

Unpacking qt5-qmake:arm64 (5.15.2+dfsg-9) ...

Unpacking qtbase5-dev-tools (5.15.2+dfsg-9) ...

Unpacking qtbase5-dev:arm64 (5.15.2+dfsg-9) ...

Unpacking subversion (1.14.1-3+deb11u1) ...

Unpacking pi-apps-c24130a9 (1.0) over (1.0) ...

Apt finished.
Package installation complete.
Downloading the Cracked-MultiMC5 Source Code directly from the official repository...
Cloning into 'src'...
error: pathspec 'develop' did not match any file(s) known to git
Could not checkout develop branch

Failed to install Cracked-MultiMC-pi-apps-master!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

**Comment by twarped** [comment]
Sorry for the insanely late response, I haven't looked at this repo for forever. I made a mistake transferring the install file over, I had it trying to install the develop branch on this repo when it should've been installing the master branch. This [commit](https://github.com/twarped/Launcher/commit/6cd6527450cf32398bbfdb334f87ace60c097883) should fix it. let me know if there are any persistent problems.
